// <auto-generated />
namespace TestUniversity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StudentTableCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentTableCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "202305101047555_StudentTableCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
